#
# Package - TODO platforms other than Linux
#
if(UNIX)
    set(CPACK_GENERATOR "DEB")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Joel Winarske")
    set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE ${PACKAGE_ARCH})
    set(CPACK_DEBIAN_PACKAGE_DEPENDS)
endif()

set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VENDOR "JoWi Electronics")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Flutter Embedder Engine - ${ENGINE_RUNTIME_MODE} ${CHANNEL}")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/cmake/files/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")
set(CPACK_PACKAGE_FILE_NAME ${PROJECT_NAME}-${ENGINE_RUNTIME_MODE}-${CHANNEL}-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${PACKAGE_ARCH})

set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})

include(CPack)
