set(CPACK_GENERATOR "TGZ;RPM;DEB")

set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VENDOR "Joel Winarske")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Flutter Embedder Engine - ${ENGINE_RUNTIME_MODE} ${FLUTTER_ENGINE_SHA}")
set(CPACK_PACKAGE_FILE_NAME ${PROJECT_NAME}-${PROJECT_VERSION}-${CMAKE_BUILD_TYPE}-${FLUTTER_ENGINE_SHA}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR})
set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})

set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Joel Winarske")
set(CPACK_DEBIAN_COMPRESSION_TYPE "lzma")

if(${CMAKE_BUILD_TYPE} STREQUAL "Release")
    set(CPACK_STRIP_FILES homescreen)
endif()

include(CPack)
